# SITE CONFIGURATION
baseurl: ""
url: "https://www.jcanfil.com"

# THEME-SPECIFIC CONFIGURATION
title: Justin Key Canfil                            # site's title
description:      # used by search engines
avatar: assets/crown2.ico                        # Empty for no avatar in navbar
favicon: assets/crown2.ico                            # Icon displayed in the tab

# Header and footer text
header_text: Welcome! 欢迎光临​！  # Change Blog header text
header_feature_image: # assets/img/triangular.jpeg

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: false
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: false                                             # Enable if using math markup
google_analytics:    "UA-54659609-3"                                   # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
